# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F:\rnd\workspace\studio_dev\tools\mayaTools\cloth\rigger\gui\_src\rigger.ui'
#
# Created: Thu Apr 07 00:08:56 2016
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_mw_rigger(object):
    def setupUi(self, mw_rigger):
        mw_rigger.setObjectName(_fromUtf8("mw_rigger"))
        mw_rigger.resize(329, 428)
        self.centralwidget = QtGui.QWidget(mw_rigger)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.qf_cloth = QtGui.QFrame(self.centralwidget)
        self.qf_cloth.setFrameShape(QtGui.QFrame.StyledPanel)
        self.qf_cloth.setObjectName(_fromUtf8("qf_cloth"))
        self.vlCloth = QtGui.QVBoxLayout(self.qf_cloth)
        self.vlCloth.setSpacing(0)
        self.vlCloth.setContentsMargins(2, 0, 2, 0)
        self.vlCloth.setObjectName(_fromUtf8("vlCloth"))
        self.hl_clothDriver = QtGui.QHBoxLayout()
        self.hl_clothDriver.setSpacing(2)
        self.hl_clothDriver.setObjectName(_fromUtf8("hl_clothDriver"))
        self.l_clothDriver = QtGui.QLabel(self.qf_cloth)
        self.l_clothDriver.setMinimumSize(QtCore.QSize(80, 0))
        self.l_clothDriver.setMaximumSize(QtCore.QSize(80, 16777215))
        self.l_clothDriver.setAlignment(QtCore.Qt.AlignCenter)
        self.l_clothDriver.setObjectName(_fromUtf8("l_clothDriver"))
        self.hl_clothDriver.addWidget(self.l_clothDriver)
        self.le_clothDriver = QtGui.QLineEdit(self.qf_cloth)
        self.le_clothDriver.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.le_clothDriver.setFrame(True)
        self.le_clothDriver.setReadOnly(True)
        self.le_clothDriver.setObjectName(_fromUtf8("le_clothDriver"))
        self.hl_clothDriver.addWidget(self.le_clothDriver)
        self.pb_pickClothDriver = QtGui.QPushButton(self.qf_cloth)
        self.pb_pickClothDriver.setMaximumSize(QtCore.QSize(16777215, 20))
        self.pb_pickClothDriver.setObjectName(_fromUtf8("pb_pickClothDriver"))
        self.hl_clothDriver.addWidget(self.pb_pickClothDriver)
        self.vlCloth.addLayout(self.hl_clothDriver)
        self.hl_clothSolver = QtGui.QHBoxLayout()
        self.hl_clothSolver.setSpacing(2)
        self.hl_clothSolver.setObjectName(_fromUtf8("hl_clothSolver"))
        self.l_clothSolver = QtGui.QLabel(self.qf_cloth)
        self.l_clothSolver.setMinimumSize(QtCore.QSize(80, 0))
        self.l_clothSolver.setMaximumSize(QtCore.QSize(80, 16777215))
        self.l_clothSolver.setAlignment(QtCore.Qt.AlignCenter)
        self.l_clothSolver.setObjectName(_fromUtf8("l_clothSolver"))
        self.hl_clothSolver.addWidget(self.l_clothSolver)
        self.cb_clothSolver = QtGui.QComboBox(self.qf_cloth)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cb_clothSolver.sizePolicy().hasHeightForWidth())
        self.cb_clothSolver.setSizePolicy(sizePolicy)
        self.cb_clothSolver.setObjectName(_fromUtf8("cb_clothSolver"))
        self.cb_clothSolver.addItem(_fromUtf8(""))
        self.hl_clothSolver.addWidget(self.cb_clothSolver)
        self.pb_clothSolverRf = QtGui.QPushButton(self.qf_cloth)
        self.pb_clothSolverRf.setMaximumSize(QtCore.QSize(16777215, 20))
        self.pb_clothSolverRf.setObjectName(_fromUtf8("pb_clothSolverRf"))
        self.hl_clothSolver.addWidget(self.pb_clothSolverRf)
        self.vlCloth.addLayout(self.hl_clothSolver)
        self.hl_clothMesh = QtGui.QHBoxLayout()
        self.hl_clothMesh.setSpacing(2)
        self.hl_clothMesh.setObjectName(_fromUtf8("hl_clothMesh"))
        self.l_clothMesh = QtGui.QLabel(self.qf_cloth)
        self.l_clothMesh.setMinimumSize(QtCore.QSize(80, 0))
        self.l_clothMesh.setMaximumSize(QtCore.QSize(80, 16777215))
        self.l_clothMesh.setAlignment(QtCore.Qt.AlignCenter)
        self.l_clothMesh.setObjectName(_fromUtf8("l_clothMesh"))
        self.hl_clothMesh.addWidget(self.l_clothMesh)
        self.le_clothMesh = QtGui.QLineEdit(self.qf_cloth)
        self.le_clothMesh.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.le_clothMesh.setFrame(True)
        self.le_clothMesh.setReadOnly(True)
        self.le_clothMesh.setObjectName(_fromUtf8("le_clothMesh"))
        self.hl_clothMesh.addWidget(self.le_clothMesh)
        self.pb_pickClothMesh = QtGui.QPushButton(self.qf_cloth)
        self.pb_pickClothMesh.setMaximumSize(QtCore.QSize(16777215, 20))
        self.pb_pickClothMesh.setObjectName(_fromUtf8("pb_pickClothMesh"))
        self.hl_clothMesh.addWidget(self.pb_pickClothMesh)
        self.vlCloth.addLayout(self.hl_clothMesh)
        self.hl_clothResult = QtGui.QHBoxLayout()
        self.hl_clothResult.setSpacing(2)
        self.hl_clothResult.setObjectName(_fromUtf8("hl_clothResult"))
        self.l_clothResult = QtGui.QLabel(self.qf_cloth)
        self.l_clothResult.setMinimumSize(QtCore.QSize(80, 0))
        self.l_clothResult.setMaximumSize(QtCore.QSize(80, 16777215))
        self.l_clothResult.setAlignment(QtCore.Qt.AlignCenter)
        self.l_clothResult.setObjectName(_fromUtf8("l_clothResult"))
        self.hl_clothResult.addWidget(self.l_clothResult)
        self.le_clothResult = QtGui.QLineEdit(self.qf_cloth)
        self.le_clothResult.setEnabled(False)
        self.le_clothResult.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.le_clothResult.setObjectName(_fromUtf8("le_clothResult"))
        self.hl_clothResult.addWidget(self.le_clothResult)
        self.vlCloth.addLayout(self.hl_clothResult)
        self.qf_clothColor = QtGui.QFrame(self.qf_cloth)
        self.qf_clothColor.setMaximumSize(QtCore.QSize(16777215, 50))
        self.qf_clothColor.setObjectName(_fromUtf8("qf_clothColor"))
        self.hl_clothColor = QtGui.QHBoxLayout(self.qf_clothColor)
        self.hl_clothColor.setSpacing(0)
        self.hl_clothColor.setMargin(0)
        self.hl_clothColor.setObjectName(_fromUtf8("hl_clothColor"))
        self.vlCloth.addWidget(self.qf_clothColor)
        self.hl_createCloth = QtGui.QHBoxLayout()
        self.hl_createCloth.setSpacing(2)
        self.hl_createCloth.setContentsMargins(-1, 0, 10, -1)
        self.hl_createCloth.setObjectName(_fromUtf8("hl_createCloth"))
        self.pb_createCloth = QtGui.QPushButton(self.qf_cloth)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_createCloth.sizePolicy().hasHeightForWidth())
        self.pb_createCloth.setSizePolicy(sizePolicy)
        self.pb_createCloth.setIconSize(QtCore.QSize(24, 24))
        self.pb_createCloth.setFlat(True)
        self.pb_createCloth.setObjectName(_fromUtf8("pb_createCloth"))
        self.hl_createCloth.addWidget(self.pb_createCloth)
        self.cb_loToHi = QtGui.QCheckBox(self.qf_cloth)
        self.cb_loToHi.setChecked(True)
        self.cb_loToHi.setObjectName(_fromUtf8("cb_loToHi"))
        self.hl_createCloth.addWidget(self.cb_loToHi)
        self.vlCloth.addLayout(self.hl_createCloth)
        self.gridLayout.addWidget(self.qf_cloth, 3, 0, 1, 1)
        self.qf_rigid = QtGui.QFrame(self.centralwidget)
        self.qf_rigid.setFrameShape(QtGui.QFrame.StyledPanel)
        self.qf_rigid.setObjectName(_fromUtf8("qf_rigid"))
        self.vlCloth_2 = QtGui.QVBoxLayout(self.qf_rigid)
        self.vlCloth_2.setSpacing(0)
        self.vlCloth_2.setContentsMargins(2, 0, 2, 0)
        self.vlCloth_2.setObjectName(_fromUtf8("vlCloth_2"))
        self.hl_rigidDriver = QtGui.QHBoxLayout()
        self.hl_rigidDriver.setSpacing(2)
        self.hl_rigidDriver.setObjectName(_fromUtf8("hl_rigidDriver"))
        self.l_rigidDriver = QtGui.QLabel(self.qf_rigid)
        self.l_rigidDriver.setMinimumSize(QtCore.QSize(80, 0))
        self.l_rigidDriver.setMaximumSize(QtCore.QSize(80, 16777215))
        self.l_rigidDriver.setAlignment(QtCore.Qt.AlignCenter)
        self.l_rigidDriver.setObjectName(_fromUtf8("l_rigidDriver"))
        self.hl_rigidDriver.addWidget(self.l_rigidDriver)
        self.le_rigidDriver = QtGui.QLineEdit(self.qf_rigid)
        self.le_rigidDriver.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.le_rigidDriver.setFrame(True)
        self.le_rigidDriver.setReadOnly(True)
        self.le_rigidDriver.setObjectName(_fromUtf8("le_rigidDriver"))
        self.hl_rigidDriver.addWidget(self.le_rigidDriver)
        self.pb_pickRigidDriver = QtGui.QPushButton(self.qf_rigid)
        self.pb_pickRigidDriver.setMaximumSize(QtCore.QSize(16777215, 20))
        self.pb_pickRigidDriver.setObjectName(_fromUtf8("pb_pickRigidDriver"))
        self.hl_rigidDriver.addWidget(self.pb_pickRigidDriver)
        self.vlCloth_2.addLayout(self.hl_rigidDriver)
        self.hl_rigidSolver = QtGui.QHBoxLayout()
        self.hl_rigidSolver.setSpacing(2)
        self.hl_rigidSolver.setObjectName(_fromUtf8("hl_rigidSolver"))
        self.l_rigidSolver = QtGui.QLabel(self.qf_rigid)
        self.l_rigidSolver.setMinimumSize(QtCore.QSize(80, 0))
        self.l_rigidSolver.setMaximumSize(QtCore.QSize(80, 16777215))
        self.l_rigidSolver.setAlignment(QtCore.Qt.AlignCenter)
        self.l_rigidSolver.setObjectName(_fromUtf8("l_rigidSolver"))
        self.hl_rigidSolver.addWidget(self.l_rigidSolver)
        self.cb_rigidSolver = QtGui.QComboBox(self.qf_rigid)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cb_rigidSolver.sizePolicy().hasHeightForWidth())
        self.cb_rigidSolver.setSizePolicy(sizePolicy)
        self.cb_rigidSolver.setObjectName(_fromUtf8("cb_rigidSolver"))
        self.cb_rigidSolver.addItem(_fromUtf8(""))
        self.hl_rigidSolver.addWidget(self.cb_rigidSolver)
        self.pb_rigidSolverRf = QtGui.QPushButton(self.qf_rigid)
        self.pb_rigidSolverRf.setMaximumSize(QtCore.QSize(16777215, 20))
        self.pb_rigidSolverRf.setObjectName(_fromUtf8("pb_rigidSolverRf"))
        self.hl_rigidSolver.addWidget(self.pb_rigidSolverRf)
        self.vlCloth_2.addLayout(self.hl_rigidSolver)
        self.hl_rigidMesh = QtGui.QHBoxLayout()
        self.hl_rigidMesh.setSpacing(2)
        self.hl_rigidMesh.setObjectName(_fromUtf8("hl_rigidMesh"))
        self.l_rigidMesh = QtGui.QLabel(self.qf_rigid)
        self.l_rigidMesh.setMinimumSize(QtCore.QSize(80, 0))
        self.l_rigidMesh.setMaximumSize(QtCore.QSize(80, 16777215))
        self.l_rigidMesh.setAlignment(QtCore.Qt.AlignCenter)
        self.l_rigidMesh.setObjectName(_fromUtf8("l_rigidMesh"))
        self.hl_rigidMesh.addWidget(self.l_rigidMesh)
        self.le_rigidMesh = QtGui.QLineEdit(self.qf_rigid)
        self.le_rigidMesh.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.le_rigidMesh.setFrame(True)
        self.le_rigidMesh.setReadOnly(True)
        self.le_rigidMesh.setObjectName(_fromUtf8("le_rigidMesh"))
        self.hl_rigidMesh.addWidget(self.le_rigidMesh)
        self.pb_pickRigidMesh = QtGui.QPushButton(self.qf_rigid)
        self.pb_pickRigidMesh.setMaximumSize(QtCore.QSize(16777215, 20))
        self.pb_pickRigidMesh.setObjectName(_fromUtf8("pb_pickRigidMesh"))
        self.hl_rigidMesh.addWidget(self.pb_pickRigidMesh)
        self.vlCloth_2.addLayout(self.hl_rigidMesh)
        self.hl_rigidResult = QtGui.QHBoxLayout()
        self.hl_rigidResult.setSpacing(2)
        self.hl_rigidResult.setObjectName(_fromUtf8("hl_rigidResult"))
        self.l_rigidResult = QtGui.QLabel(self.qf_rigid)
        self.l_rigidResult.setMinimumSize(QtCore.QSize(80, 0))
        self.l_rigidResult.setMaximumSize(QtCore.QSize(80, 16777215))
        self.l_rigidResult.setAlignment(QtCore.Qt.AlignCenter)
        self.l_rigidResult.setObjectName(_fromUtf8("l_rigidResult"))
        self.hl_rigidResult.addWidget(self.l_rigidResult)
        self.le_rigidResult = QtGui.QLineEdit(self.qf_rigid)
        self.le_rigidResult.setEnabled(False)
        self.le_rigidResult.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.le_rigidResult.setObjectName(_fromUtf8("le_rigidResult"))
        self.hl_rigidResult.addWidget(self.le_rigidResult)
        self.vlCloth_2.addLayout(self.hl_rigidResult)
        self.hl_rigidMode = QtGui.QHBoxLayout()
        self.hl_rigidMode.setSpacing(2)
        self.hl_rigidMode.setObjectName(_fromUtf8("hl_rigidMode"))
        self.l_rigidMode = QtGui.QLabel(self.qf_rigid)
        self.l_rigidMode.setMinimumSize(QtCore.QSize(80, 0))
        self.l_rigidMode.setMaximumSize(QtCore.QSize(80, 16777215))
        self.l_rigidMode.setAlignment(QtCore.Qt.AlignCenter)
        self.l_rigidMode.setObjectName(_fromUtf8("l_rigidMode"))
        self.hl_rigidMode.addWidget(self.l_rigidMode)
        self.rb_collide = QtGui.QRadioButton(self.qf_rigid)
        self.rb_collide.setChecked(True)
        self.rb_collide.setObjectName(_fromUtf8("rb_collide"))
        self.hl_rigidMode.addWidget(self.rb_collide)
        self.rb_pushOut = QtGui.QRadioButton(self.qf_rigid)
        self.rb_pushOut.setObjectName(_fromUtf8("rb_pushOut"))
        self.hl_rigidMode.addWidget(self.rb_pushOut)
        self.rb_passive = QtGui.QRadioButton(self.qf_rigid)
        self.rb_passive.setObjectName(_fromUtf8("rb_passive"))
        self.hl_rigidMode.addWidget(self.rb_passive)
        self.vlCloth_2.addLayout(self.hl_rigidMode)
        self.qf_rigidColor = QtGui.QFrame(self.qf_rigid)
        self.qf_rigidColor.setMaximumSize(QtCore.QSize(16777215, 50))
        self.qf_rigidColor.setLineWidth(0)
        self.qf_rigidColor.setObjectName(_fromUtf8("qf_rigidColor"))
        self.hl_rigidColor = QtGui.QHBoxLayout(self.qf_rigidColor)
        self.hl_rigidColor.setSpacing(0)
        self.hl_rigidColor.setMargin(0)
        self.hl_rigidColor.setObjectName(_fromUtf8("hl_rigidColor"))
        self.vlCloth_2.addWidget(self.qf_rigidColor)
        self.hl_createRigid = QtGui.QHBoxLayout()
        self.hl_createRigid.setSpacing(2)
        self.hl_createRigid.setContentsMargins(-1, 0, -1, -1)
        self.hl_createRigid.setObjectName(_fromUtf8("hl_createRigid"))
        self.pb_createRigid = QtGui.QPushButton(self.qf_rigid)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_createRigid.sizePolicy().hasHeightForWidth())
        self.pb_createRigid.setSizePolicy(sizePolicy)
        self.pb_createRigid.setIconSize(QtCore.QSize(24, 24))
        self.pb_createRigid.setFlat(True)
        self.pb_createRigid.setObjectName(_fromUtf8("pb_createRigid"))
        self.hl_createRigid.addWidget(self.pb_createRigid)
        self.cb_smoothMesh = QtGui.QCheckBox(self.qf_rigid)
        self.cb_smoothMesh.setObjectName(_fromUtf8("cb_smoothMesh"))
        self.hl_createRigid.addWidget(self.cb_smoothMesh)
        self.vlCloth_2.addLayout(self.hl_createRigid)
        self.gridLayout.addWidget(self.qf_rigid, 5, 0, 1, 1)
        self.line_2 = QtGui.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.gridLayout.addWidget(self.line_2, 4, 0, 1, 1)
        self.qf_constraint = QtGui.QFrame(self.centralwidget)
        self.qf_constraint.setFrameShape(QtGui.QFrame.StyledPanel)
        self.qf_constraint.setObjectName(_fromUtf8("qf_constraint"))
        self.verticalLayout = QtGui.QVBoxLayout(self.qf_constraint)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setContentsMargins(2, 0, 2, 0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.hl_constraint = QtGui.QHBoxLayout()
        self.hl_constraint.setSpacing(2)
        self.hl_constraint.setObjectName(_fromUtf8("hl_constraint"))
        self.l_constraint = QtGui.QLabel(self.qf_constraint)
        self.l_constraint.setMinimumSize(QtCore.QSize(80, 0))
        self.l_constraint.setMaximumSize(QtCore.QSize(80, 16777215))
        self.l_constraint.setAlignment(QtCore.Qt.AlignCenter)
        self.l_constraint.setObjectName(_fromUtf8("l_constraint"))
        self.hl_constraint.addWidget(self.l_constraint)
        self.le_constraint = QtGui.QLineEdit(self.qf_constraint)
        self.le_constraint.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.le_constraint.setFrame(True)
        self.le_constraint.setReadOnly(True)
        self.le_constraint.setObjectName(_fromUtf8("le_constraint"))
        self.hl_constraint.addWidget(self.le_constraint)
        self.pb_pickConstraint = QtGui.QPushButton(self.qf_constraint)
        self.pb_pickConstraint.setMaximumSize(QtCore.QSize(16777215, 20))
        self.pb_pickConstraint.setObjectName(_fromUtf8("pb_pickConstraint"))
        self.hl_constraint.addWidget(self.pb_pickConstraint)
        self.verticalLayout.addLayout(self.hl_constraint)
        self.hl_constResult = QtGui.QHBoxLayout()
        self.hl_constResult.setSpacing(2)
        self.hl_constResult.setObjectName(_fromUtf8("hl_constResult"))
        self.l_constResult = QtGui.QLabel(self.qf_constraint)
        self.l_constResult.setMinimumSize(QtCore.QSize(80, 0))
        self.l_constResult.setMaximumSize(QtCore.QSize(80, 16777215))
        self.l_constResult.setAlignment(QtCore.Qt.AlignCenter)
        self.l_constResult.setObjectName(_fromUtf8("l_constResult"))
        self.hl_constResult.addWidget(self.l_constResult)
        self.le_constResult = QtGui.QLineEdit(self.qf_constraint)
        self.le_constResult.setEnabled(False)
        self.le_constResult.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.le_constResult.setObjectName(_fromUtf8("le_constResult"))
        self.hl_constResult.addWidget(self.le_constResult)
        self.verticalLayout.addLayout(self.hl_constResult)
        self.pb_storeConst = QtGui.QPushButton(self.qf_constraint)
        self.pb_storeConst.setIconSize(QtCore.QSize(24, 24))
        self.pb_storeConst.setFlat(True)
        self.pb_storeConst.setObjectName(_fromUtf8("pb_storeConst"))
        self.verticalLayout.addWidget(self.pb_storeConst)
        self.gridLayout.addWidget(self.qf_constraint, 7, 0, 1, 1)
        self.line_3 = QtGui.QFrame(self.centralwidget)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.gridLayout.addWidget(self.line_3, 6, 0, 1, 1)
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout.addWidget(self.line, 0, 0, 1, 1)
        self.line_4 = QtGui.QFrame(self.centralwidget)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.gridLayout.addWidget(self.line_4, 2, 0, 1, 1)
        self.gb_initWraps = QtGui.QGroupBox(self.centralwidget)
        self.gb_initWraps.setMaximumSize(QtCore.QSize(16777215, 200))
        self.gb_initWraps.setFlat(False)
        self.gb_initWraps.setCheckable(True)
        self.gb_initWraps.setChecked(False)
        self.gb_initWraps.setObjectName(_fromUtf8("gb_initWraps"))
        self.gridLayout_2 = QtGui.QGridLayout(self.gb_initWraps)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.qf_driverWrap = QtGui.QFrame(self.gb_initWraps)
        self.qf_driverWrap.setFrameShape(QtGui.QFrame.StyledPanel)
        self.qf_driverWrap.setObjectName(_fromUtf8("qf_driverWrap"))
        self.vl_driverWrap = QtGui.QVBoxLayout(self.qf_driverWrap)
        self.vl_driverWrap.setSpacing(0)
        self.vl_driverWrap.setMargin(0)
        self.vl_driverWrap.setObjectName(_fromUtf8("vl_driverWrap"))
        self.l_driverWraps = QtGui.QLabel(self.qf_driverWrap)
        font = QtGui.QFont()
        font.setUnderline(True)
        self.l_driverWraps.setFont(font)
        self.l_driverWraps.setAlignment(QtCore.Qt.AlignCenter)
        self.l_driverWraps.setObjectName(_fromUtf8("l_driverWraps"))
        self.vl_driverWrap.addWidget(self.l_driverWraps)
        self.hl_driverWrap = QtGui.QHBoxLayout()
        self.hl_driverWrap.setSpacing(0)
        self.hl_driverWrap.setObjectName(_fromUtf8("hl_driverWrap"))
        self.pb_hiToDecoupe = QtGui.QPushButton(self.qf_driverWrap)
        self.pb_hiToDecoupe.setObjectName(_fromUtf8("pb_hiToDecoupe"))
        self.hl_driverWrap.addWidget(self.pb_hiToDecoupe)
        self.line_5 = QtGui.QFrame(self.qf_driverWrap)
        self.line_5.setFrameShape(QtGui.QFrame.VLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.hl_driverWrap.addWidget(self.line_5)
        self.pb_losToDecoupe = QtGui.QPushButton(self.qf_driverWrap)
        self.pb_losToDecoupe.setObjectName(_fromUtf8("pb_losToDecoupe"))
        self.hl_driverWrap.addWidget(self.pb_losToDecoupe)
        self.vl_driverWrap.addLayout(self.hl_driverWrap)
        self.gridLayout_2.addWidget(self.qf_driverWrap, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.gb_initWraps, 1, 0, 1, 1)
        mw_rigger.setCentralWidget(self.centralwidget)
        self.menuBar = QtGui.QMenuBar(mw_rigger)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 329, 24))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.m_menu = QtGui.QMenu(self.menuBar)
        self.m_menu.setObjectName(_fromUtf8("m_menu"))
        mw_rigger.setMenuBar(self.menuBar)
        self.mi_help = QtGui.QAction(mw_rigger)
        self.mi_help.setObjectName(_fromUtf8("mi_help"))
        self.m_menu.addAction(self.mi_help)
        self.menuBar.addAction(self.m_menu.menuAction())

        self.retranslateUi(mw_rigger)
        QtCore.QMetaObject.connectSlotsByName(mw_rigger)

    def retranslateUi(self, mw_rigger):
        mw_rigger.setWindowTitle(_translate("mw_rigger", "Rigger", None))
        self.l_clothDriver.setText(_translate("mw_rigger", "Cloth Driver: ", None))
        self.pb_pickClothDriver.setText(_translate("mw_rigger", "Pick", None))
        self.l_clothSolver.setText(_translate("mw_rigger", "Solver: ", None))
        self.cb_clothSolver.setItemText(0, _translate("mw_rigger", "New Nucleus", None))
        self.pb_clothSolverRf.setText(_translate("mw_rigger", "Refresh", None))
        self.l_clothMesh.setText(_translate("mw_rigger", "Cloth Mesh: ", None))
        self.pb_pickClothMesh.setText(_translate("mw_rigger", "Pick", None))
        self.l_clothResult.setText(_translate("mw_rigger", "Result: ", None))
        self.pb_createCloth.setText(_translate("mw_rigger", "Create Cloth", None))
        self.cb_loToHi.setText(_translate("mw_rigger", "Lo To Hi", None))
        self.l_rigidDriver.setText(_translate("mw_rigger", "Rigid Driver: ", None))
        self.pb_pickRigidDriver.setText(_translate("mw_rigger", "Pick", None))
        self.l_rigidSolver.setText(_translate("mw_rigger", "Solver: ", None))
        self.cb_rigidSolver.setItemText(0, _translate("mw_rigger", "New Nucleus", None))
        self.pb_rigidSolverRf.setText(_translate("mw_rigger", "Refresh", None))
        self.l_rigidMesh.setText(_translate("mw_rigger", "Rigid Mesh: ", None))
        self.pb_pickRigidMesh.setText(_translate("mw_rigger", "Pick", None))
        self.l_rigidResult.setText(_translate("mw_rigger", "Result: ", None))
        self.l_rigidMode.setText(_translate("mw_rigger", "Mode: ", None))
        self.rb_collide.setText(_translate("mw_rigger", "Collide", None))
        self.rb_pushOut.setText(_translate("mw_rigger", "PushOut", None))
        self.rb_passive.setText(_translate("mw_rigger", "Passive", None))
        self.pb_createRigid.setText(_translate("mw_rigger", "Create Rigid", None))
        self.cb_smoothMesh.setText(_translate("mw_rigger", "Smooth Mesh", None))
        self.l_constraint.setText(_translate("mw_rigger", "Dyn Constraint: ", None))
        self.pb_pickConstraint.setText(_translate("mw_rigger", "Pick", None))
        self.l_constResult.setText(_translate("mw_rigger", "Result: ", None))
        self.pb_storeConst.setText(_translate("mw_rigger", "Store Constraint", None))
        self.gb_initWraps.setTitle(_translate("mw_rigger", "Init Wraps", None))
        self.l_driverWraps.setText(_translate("mw_rigger", "Driver Wraps;", None))
        self.pb_hiToDecoupe.setText(_translate("mw_rigger", "Hi To Decoupe", None))
        self.pb_losToDecoupe.setText(_translate("mw_rigger", "Los To Decoupe", None))
        self.m_menu.setTitle(_translate("mw_rigger", "Menu", None))
        self.mi_help.setText(_translate("mw_rigger", "Help", None))

