# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F:\rnd\workspace\studio_dev\appli\foundation\gui\_src\loadProject.ui'
#
# Created: Sun Feb 14 15:23:04 2016
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(326, 355)
        self.gridLayout = QtGui.QGridLayout(Dialog)
        self.gridLayout.setMargin(0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.line = QtGui.QFrame(Dialog)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout.addWidget(self.line, 0, 0, 1, 1)
        self.hl_buttons = QtGui.QHBoxLayout()
        self.hl_buttons.setSpacing(0)
        self.hl_buttons.setObjectName(_fromUtf8("hl_buttons"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hl_buttons.addItem(spacerItem)
        self.pb_cancel = QtGui.QPushButton(Dialog)
        self.pb_cancel.setMinimumSize(QtCore.QSize(60, 0))
        self.pb_cancel.setMaximumSize(QtCore.QSize(60, 16777215))
        self.pb_cancel.setAutoDefault(True)
        self.pb_cancel.setFlat(False)
        self.pb_cancel.setObjectName(_fromUtf8("pb_cancel"))
        self.hl_buttons.addWidget(self.pb_cancel)
        self.gridLayout.addLayout(self.hl_buttons, 7, 0, 1, 1)
        self.line_2 = QtGui.QFrame(Dialog)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.gridLayout.addWidget(self.line_2, 2, 0, 1, 1)
        self.l_loadProject = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.l_loadProject.setFont(font)
        self.l_loadProject.setAlignment(QtCore.Qt.AlignCenter)
        self.l_loadProject.setObjectName(_fromUtf8("l_loadProject"))
        self.gridLayout.addWidget(self.l_loadProject, 1, 0, 1, 1)
        self.pb_load = QtGui.QPushButton(Dialog)
        self.pb_load.setMinimumSize(QtCore.QSize(0, 0))
        self.pb_load.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pb_load.setAutoDefault(True)
        self.pb_load.setFlat(False)
        self.pb_load.setObjectName(_fromUtf8("pb_load"))
        self.gridLayout.addWidget(self.pb_load, 5, 0, 1, 1)
        self.line_3 = QtGui.QFrame(Dialog)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.gridLayout.addWidget(self.line_3, 6, 0, 1, 1)
        self.line_4 = QtGui.QFrame(Dialog)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.gridLayout.addWidget(self.line_4, 4, 0, 1, 1)
        self.tabWidget = QtGui.QTabWidget(Dialog)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_allProjects = QtGui.QWidget()
        self.tab_allProjects.setObjectName(_fromUtf8("tab_allProjects"))
        self.gl_allProjects = QtGui.QGridLayout(self.tab_allProjects)
        self.gl_allProjects.setMargin(0)
        self.gl_allProjects.setSpacing(0)
        self.gl_allProjects.setObjectName(_fromUtf8("gl_allProjects"))
        self.tw_allProjects = QtGui.QTreeWidget(self.tab_allProjects)
        self.tw_allProjects.setFrameShape(QtGui.QFrame.NoFrame)
        self.tw_allProjects.setAlternatingRowColors(True)
        self.tw_allProjects.setIndentation(0)
        self.tw_allProjects.setItemsExpandable(False)
        self.tw_allProjects.setExpandsOnDoubleClick(False)
        self.tw_allProjects.setObjectName(_fromUtf8("tw_allProjects"))
        self.tw_allProjects.headerItem().setTextAlignment(0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tw_allProjects.headerItem().setTextAlignment(1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tw_allProjects.header().setVisible(True)
        self.tw_allProjects.header().setStretchLastSection(False)
        self.gl_allProjects.addWidget(self.tw_allProjects, 3, 0, 1, 1)
        self.line_8 = QtGui.QFrame(self.tab_allProjects)
        self.line_8.setFrameShape(QtGui.QFrame.HLine)
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setObjectName(_fromUtf8("line_8"))
        self.gl_allProjects.addWidget(self.line_8, 2, 0, 1, 1)
        self.pb_store = QtGui.QPushButton(self.tab_allProjects)
        self.pb_store.setAutoDefault(True)
        self.pb_store.setFlat(False)
        self.pb_store.setObjectName(_fromUtf8("pb_store"))
        self.gl_allProjects.addWidget(self.pb_store, 1, 0, 1, 1)
        self.line_10 = QtGui.QFrame(self.tab_allProjects)
        self.line_10.setFrameShape(QtGui.QFrame.HLine)
        self.line_10.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_10.setObjectName(_fromUtf8("line_10"))
        self.gl_allProjects.addWidget(self.line_10, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_allProjects, _fromUtf8(""))
        self.tab_myProjects = QtGui.QWidget()
        self.tab_myProjects.setObjectName(_fromUtf8("tab_myProjects"))
        self.gl_myProjects = QtGui.QGridLayout(self.tab_myProjects)
        self.gl_myProjects.setMargin(0)
        self.gl_myProjects.setSpacing(0)
        self.gl_myProjects.setObjectName(_fromUtf8("gl_myProjects"))
        self.line_11 = QtGui.QFrame(self.tab_myProjects)
        self.line_11.setFrameShape(QtGui.QFrame.HLine)
        self.line_11.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_11.setObjectName(_fromUtf8("line_11"))
        self.gl_myProjects.addWidget(self.line_11, 0, 0, 1, 1)
        self.line_9 = QtGui.QFrame(self.tab_myProjects)
        self.line_9.setFrameShape(QtGui.QFrame.HLine)
        self.line_9.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_9.setObjectName(_fromUtf8("line_9"))
        self.gl_myProjects.addWidget(self.line_9, 3, 0, 1, 1)
        self.hl_options = QtGui.QHBoxLayout()
        self.hl_options.setSpacing(0)
        self.hl_options.setObjectName(_fromUtf8("hl_options"))
        self.pb_remove = QtGui.QPushButton(self.tab_myProjects)
        self.pb_remove.setAutoDefault(True)
        self.pb_remove.setFlat(False)
        self.pb_remove.setObjectName(_fromUtf8("pb_remove"))
        self.hl_options.addWidget(self.pb_remove)
        self.pb_refresh = QtGui.QPushButton(self.tab_myProjects)
        self.pb_refresh.setAutoDefault(True)
        self.pb_refresh.setFlat(False)
        self.pb_refresh.setObjectName(_fromUtf8("pb_refresh"))
        self.hl_options.addWidget(self.pb_refresh)
        self.gl_myProjects.addLayout(self.hl_options, 1, 0, 1, 1)
        self.tw_myProjects = QtGui.QTreeWidget(self.tab_myProjects)
        self.tw_myProjects.setFrameShape(QtGui.QFrame.NoFrame)
        self.tw_myProjects.setAlternatingRowColors(True)
        self.tw_myProjects.setIndentation(0)
        self.tw_myProjects.setItemsExpandable(False)
        self.tw_myProjects.setExpandsOnDoubleClick(False)
        self.tw_myProjects.setObjectName(_fromUtf8("tw_myProjects"))
        self.tw_myProjects.headerItem().setTextAlignment(0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tw_myProjects.headerItem().setTextAlignment(1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tw_myProjects.header().setVisible(False)
        self.tw_myProjects.header().setStretchLastSection(False)
        self.gl_myProjects.addWidget(self.tw_myProjects, 2, 0, 1, 1)
        self.tabWidget.addTab(self.tab_myProjects, _fromUtf8(""))
        self.gridLayout.addWidget(self.tabWidget, 3, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Load Project", None))
        self.pb_cancel.setText(_translate("Dialog", "Cancel", None))
        self.l_loadProject.setText(_translate("Dialog", "Load Project", None))
        self.pb_load.setText(_translate("Dialog", "Load Project", None))
        self.tw_allProjects.setSortingEnabled(True)
        self.tw_allProjects.headerItem().setText(0, _translate("Dialog", "Project Name", None))
        self.tw_allProjects.headerItem().setText(1, _translate("Dialog", "Project Code", None))
        self.pb_store.setText(_translate("Dialog", "Store In \'My Projects\'", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_allProjects), _translate("Dialog", "All Projects", None))
        self.pb_remove.setText(_translate("Dialog", "Remove From \'My Projects\'", None))
        self.pb_refresh.setText(_translate("Dialog", "Refresh", None))
        self.tw_myProjects.setSortingEnabled(True)
        self.tw_myProjects.headerItem().setText(0, _translate("Dialog", "Project Name", None))
        self.tw_myProjects.headerItem().setText(1, _translate("Dialog", "Project Code", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_myProjects), _translate("Dialog", "My Projects", None))

