# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F:\rnd\workspace\studio_dev\appli\foundation\gui\_src\ts_contextDial.ui'
#
# Created: Sat Feb 27 15:10:06 2016
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_dial_context(object):
    def setupUi(self, dial_context):
        dial_context.setObjectName(_fromUtf8("dial_context"))
        dial_context.resize(318, 147)
        self.gridLayout = QtGui.QGridLayout(dial_context)
        self.gridLayout.setMargin(0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.line_5 = QtGui.QFrame(dial_context)
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.gridLayout.addWidget(self.line_5, 6, 0, 1, 1)
        self.hl_buttons = QtGui.QHBoxLayout()
        self.hl_buttons.setSpacing(0)
        self.hl_buttons.setObjectName(_fromUtf8("hl_buttons"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hl_buttons.addItem(spacerItem)
        self.pb_save = QtGui.QPushButton(dial_context)
        self.pb_save.setMinimumSize(QtCore.QSize(60, 0))
        self.pb_save.setMaximumSize(QtCore.QSize(60, 16777215))
        self.pb_save.setAutoDefault(True)
        self.pb_save.setFlat(False)
        self.pb_save.setObjectName(_fromUtf8("pb_save"))
        self.hl_buttons.addWidget(self.pb_save)
        self.pb_cancel = QtGui.QPushButton(dial_context)
        self.pb_cancel.setMinimumSize(QtCore.QSize(60, 0))
        self.pb_cancel.setMaximumSize(QtCore.QSize(60, 16777215))
        self.pb_cancel.setAutoDefault(True)
        self.pb_cancel.setFlat(False)
        self.pb_cancel.setObjectName(_fromUtf8("pb_cancel"))
        self.hl_buttons.addWidget(self.pb_cancel)
        self.gridLayout.addLayout(self.hl_buttons, 11, 0, 1, 1)
        self.line_2 = QtGui.QFrame(dial_context)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.gridLayout.addWidget(self.line_2, 2, 0, 1, 1)
        self.l_newContext = QtGui.QLabel(dial_context)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.l_newContext.setFont(font)
        self.l_newContext.setAlignment(QtCore.Qt.AlignCenter)
        self.l_newContext.setObjectName(_fromUtf8("l_newContext"))
        self.gridLayout.addWidget(self.l_newContext, 1, 0, 1, 1)
        self.line_3 = QtGui.QFrame(dial_context)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.gridLayout.addWidget(self.line_3, 10, 0, 1, 1)
        self.line = QtGui.QFrame(dial_context)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout.addWidget(self.line, 0, 0, 1, 1)
        self.hl_contextType = QtGui.QHBoxLayout()
        self.hl_contextType.setContentsMargins(6, -1, 0, -1)
        self.hl_contextType.setObjectName(_fromUtf8("hl_contextType"))
        self.l_contextType = QtGui.QLabel(dial_context)
        self.l_contextType.setMinimumSize(QtCore.QSize(72, 0))
        self.l_contextType.setMaximumSize(QtCore.QSize(72, 16777215))
        self.l_contextType.setObjectName(_fromUtf8("l_contextType"))
        self.hl_contextType.addWidget(self.l_contextType)
        self.le_contextType = QtGui.QLineEdit(dial_context)
        self.le_contextType.setMouseTracking(False)
        self.le_contextType.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.le_contextType.setFrame(False)
        self.le_contextType.setEchoMode(QtGui.QLineEdit.Normal)
        self.le_contextType.setObjectName(_fromUtf8("le_contextType"))
        self.hl_contextType.addWidget(self.le_contextType)
        self.gridLayout.addLayout(self.hl_contextType, 3, 0, 1, 1)
        self.hl_contextCode = QtGui.QHBoxLayout()
        self.hl_contextCode.setContentsMargins(6, -1, 0, -1)
        self.hl_contextCode.setObjectName(_fromUtf8("hl_contextCode"))
        self.l_contextCode = QtGui.QLabel(dial_context)
        self.l_contextCode.setMinimumSize(QtCore.QSize(72, 0))
        self.l_contextCode.setMaximumSize(QtCore.QSize(72, 16777215))
        self.l_contextCode.setObjectName(_fromUtf8("l_contextCode"))
        self.hl_contextCode.addWidget(self.l_contextCode)
        self.le_contextCode = QtGui.QLineEdit(dial_context)
        self.le_contextCode.setMouseTracking(False)
        self.le_contextCode.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.le_contextCode.setFrame(False)
        self.le_contextCode.setEchoMode(QtGui.QLineEdit.Normal)
        self.le_contextCode.setObjectName(_fromUtf8("le_contextCode"))
        self.hl_contextCode.addWidget(self.le_contextCode)
        self.gridLayout.addLayout(self.hl_contextCode, 5, 0, 1, 1)
        self.line_4 = QtGui.QFrame(dial_context)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.gridLayout.addWidget(self.line_4, 4, 0, 1, 1)
        self.hl_contextLabel = QtGui.QHBoxLayout()
        self.hl_contextLabel.setContentsMargins(6, -1, 0, -1)
        self.hl_contextLabel.setObjectName(_fromUtf8("hl_contextLabel"))
        self.l_contextLabel = QtGui.QLabel(dial_context)
        self.l_contextLabel.setMinimumSize(QtCore.QSize(72, 0))
        self.l_contextLabel.setMaximumSize(QtCore.QSize(72, 16777215))
        self.l_contextLabel.setObjectName(_fromUtf8("l_contextLabel"))
        self.hl_contextLabel.addWidget(self.l_contextLabel)
        self.le_contextLabel = QtGui.QLineEdit(dial_context)
        self.le_contextLabel.setMouseTracking(False)
        self.le_contextLabel.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.le_contextLabel.setFrame(False)
        self.le_contextLabel.setEchoMode(QtGui.QLineEdit.Normal)
        self.le_contextLabel.setObjectName(_fromUtf8("le_contextLabel"))
        self.hl_contextLabel.addWidget(self.le_contextLabel)
        self.gridLayout.addLayout(self.hl_contextLabel, 7, 0, 1, 1)
        self.hl_contextFolder = QtGui.QHBoxLayout()
        self.hl_contextFolder.setContentsMargins(6, -1, 0, -1)
        self.hl_contextFolder.setObjectName(_fromUtf8("hl_contextFolder"))
        self.l_contextFolder = QtGui.QLabel(dial_context)
        self.l_contextFolder.setMinimumSize(QtCore.QSize(72, 0))
        self.l_contextFolder.setMaximumSize(QtCore.QSize(72, 16777215))
        self.l_contextFolder.setObjectName(_fromUtf8("l_contextFolder"))
        self.hl_contextFolder.addWidget(self.l_contextFolder)
        self.le_contextFolder = QtGui.QLineEdit(dial_context)
        self.le_contextFolder.setMouseTracking(False)
        self.le_contextFolder.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.le_contextFolder.setFrame(False)
        self.le_contextFolder.setEchoMode(QtGui.QLineEdit.Normal)
        self.le_contextFolder.setObjectName(_fromUtf8("le_contextFolder"))
        self.hl_contextFolder.addWidget(self.le_contextFolder)
        self.gridLayout.addLayout(self.hl_contextFolder, 9, 0, 1, 1)
        self.line_6 = QtGui.QFrame(dial_context)
        self.line_6.setFrameShape(QtGui.QFrame.HLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.gridLayout.addWidget(self.line_6, 8, 0, 1, 1)

        self.retranslateUi(dial_context)
        QtCore.QMetaObject.connectSlotsByName(dial_context)
        dial_context.setTabOrder(self.le_contextType, self.le_contextCode)
        dial_context.setTabOrder(self.le_contextCode, self.pb_save)
        dial_context.setTabOrder(self.pb_save, self.pb_cancel)

    def retranslateUi(self, dial_context):
        dial_context.setWindowTitle(_translate("dial_context", "Context", None))
        self.pb_save.setText(_translate("dial_context", "Save", None))
        self.pb_cancel.setText(_translate("dial_context", "Cancel", None))
        self.l_newContext.setText(_translate("dial_context", "New Context", None))
        self.l_contextType.setText(_translate("dial_context", "Context Type: ", None))
        self.l_contextCode.setText(_translate("dial_context", "Context Code: ", None))
        self.l_contextLabel.setText(_translate("dial_context", "Context Label: ", None))
        self.l_contextFolder.setText(_translate("dial_context", "Context Folder: ", None))

