# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F:\rnd\workspace\studio_dev\appli\foundation\gui\_src\ts_groupsDial.ui'
#
# Created: Sun Feb 14 11:56:13 2016
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_dial_groups(object):
    def setupUi(self, dial_groups):
        dial_groups.setObjectName(_fromUtf8("dial_groups"))
        dial_groups.resize(422, 207)
        self.gridLayout = QtGui.QGridLayout(dial_groups)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        spacerItem = QtGui.QSpacerItem(20, 13, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 8, 0, 1, 1)
        self.line_3 = QtGui.QFrame(dial_groups)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.gridLayout.addWidget(self.line_3, 0, 0, 1, 1)
        self.line_2 = QtGui.QFrame(dial_groups)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.gridLayout.addWidget(self.line_2, 2, 0, 1, 1)
        self.line = QtGui.QFrame(dial_groups)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout.addWidget(self.line, 7, 0, 1, 1)
        self.hl_buttons = QtGui.QHBoxLayout()
        self.hl_buttons.setSpacing(0)
        self.hl_buttons.setObjectName(_fromUtf8("hl_buttons"))
        spacerItem1 = QtGui.QSpacerItem(40, 10, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hl_buttons.addItem(spacerItem1)
        self.pb_save = QtGui.QPushButton(dial_groups)
        self.pb_save.setMaximumSize(QtCore.QSize(60, 20))
        self.pb_save.setObjectName(_fromUtf8("pb_save"))
        self.hl_buttons.addWidget(self.pb_save)
        self.pb_cancel = QtGui.QPushButton(dial_groups)
        self.pb_cancel.setMaximumSize(QtCore.QSize(60, 20))
        self.pb_cancel.setObjectName(_fromUtf8("pb_cancel"))
        self.hl_buttons.addWidget(self.pb_cancel)
        self.gridLayout.addLayout(self.hl_buttons, 9, 0, 1, 1)
        self.hl_userGrpStyle = QtGui.QHBoxLayout()
        self.hl_userGrpStyle.setObjectName(_fromUtf8("hl_userGrpStyle"))
        self.l_userGrpStyle = QtGui.QLabel(dial_groups)
        self.l_userGrpStyle.setMinimumSize(QtCore.QSize(92, 0))
        self.l_userGrpStyle.setMaximumSize(QtCore.QSize(92, 16777215))
        self.l_userGrpStyle.setObjectName(_fromUtf8("l_userGrpStyle"))
        self.hl_userGrpStyle.addWidget(self.l_userGrpStyle)
        self.l_r = QtGui.QLabel(dial_groups)
        self.l_r.setObjectName(_fromUtf8("l_r"))
        self.hl_userGrpStyle.addWidget(self.l_r)
        self.sb_styleR = QtGui.QSpinBox(dial_groups)
        self.sb_styleR.setMinimumSize(QtCore.QSize(30, 0))
        self.sb_styleR.setAlignment(QtCore.Qt.AlignCenter)
        self.sb_styleR.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.sb_styleR.setPrefix(_fromUtf8(""))
        self.sb_styleR.setMaximum(255)
        self.sb_styleR.setObjectName(_fromUtf8("sb_styleR"))
        self.hl_userGrpStyle.addWidget(self.sb_styleR)
        spacerItem2 = QtGui.QSpacerItem(12, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.hl_userGrpStyle.addItem(spacerItem2)
        self.l_g = QtGui.QLabel(dial_groups)
        self.l_g.setObjectName(_fromUtf8("l_g"))
        self.hl_userGrpStyle.addWidget(self.l_g)
        self.sb_styleG = QtGui.QSpinBox(dial_groups)
        self.sb_styleG.setMinimumSize(QtCore.QSize(30, 0))
        self.sb_styleG.setAlignment(QtCore.Qt.AlignCenter)
        self.sb_styleG.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.sb_styleG.setMaximum(255)
        self.sb_styleG.setObjectName(_fromUtf8("sb_styleG"))
        self.hl_userGrpStyle.addWidget(self.sb_styleG)
        spacerItem3 = QtGui.QSpacerItem(12, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.hl_userGrpStyle.addItem(spacerItem3)
        self.l_b = QtGui.QLabel(dial_groups)
        self.l_b.setObjectName(_fromUtf8("l_b"))
        self.hl_userGrpStyle.addWidget(self.l_b)
        self.sb_styleB = QtGui.QSpinBox(dial_groups)
        self.sb_styleB.setMinimumSize(QtCore.QSize(30, 0))
        self.sb_styleB.setAlignment(QtCore.Qt.AlignCenter)
        self.sb_styleB.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.sb_styleB.setMaximum(255)
        self.sb_styleB.setObjectName(_fromUtf8("sb_styleB"))
        self.hl_userGrpStyle.addWidget(self.sb_styleB)
        spacerItem4 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.hl_userGrpStyle.addItem(spacerItem4)
        self.pb_userGrpStyle = QtGui.QPushButton(dial_groups)
        self.pb_userGrpStyle.setMaximumSize(QtCore.QSize(20, 20))
        self.pb_userGrpStyle.setText(_fromUtf8(""))
        self.pb_userGrpStyle.setAutoDefault(False)
        self.pb_userGrpStyle.setFlat(False)
        self.pb_userGrpStyle.setObjectName(_fromUtf8("pb_userGrpStyle"))
        self.hl_userGrpStyle.addWidget(self.pb_userGrpStyle)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hl_userGrpStyle.addItem(spacerItem5)
        self.gridLayout.addLayout(self.hl_userGrpStyle, 6, 0, 1, 1)
        self.l_message = QtGui.QLabel(dial_groups)
        self.l_message.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.l_message.setFont(font)
        self.l_message.setAlignment(QtCore.Qt.AlignCenter)
        self.l_message.setObjectName(_fromUtf8("l_message"))
        self.gridLayout.addWidget(self.l_message, 1, 0, 1, 1)
        self.hl_userGrpCode = QtGui.QHBoxLayout()
        self.hl_userGrpCode.setObjectName(_fromUtf8("hl_userGrpCode"))
        self.l_userGrpCode = QtGui.QLabel(dial_groups)
        self.l_userGrpCode.setMinimumSize(QtCore.QSize(92, 0))
        self.l_userGrpCode.setMaximumSize(QtCore.QSize(92, 16777215))
        self.l_userGrpCode.setObjectName(_fromUtf8("l_userGrpCode"))
        self.hl_userGrpCode.addWidget(self.l_userGrpCode)
        self.le_userGrpCode = QtGui.QLineEdit(dial_groups)
        self.le_userGrpCode.setMinimumSize(QtCore.QSize(100, 0))
        self.le_userGrpCode.setMaximumSize(QtCore.QSize(100, 16777215))
        self.le_userGrpCode.setFrame(False)
        self.le_userGrpCode.setObjectName(_fromUtf8("le_userGrpCode"))
        self.hl_userGrpCode.addWidget(self.le_userGrpCode)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hl_userGrpCode.addItem(spacerItem6)
        self.gridLayout.addLayout(self.hl_userGrpCode, 3, 0, 1, 1)
        self.hl_userGrpName = QtGui.QHBoxLayout()
        self.hl_userGrpName.setObjectName(_fromUtf8("hl_userGrpName"))
        self.l_userGrpName = QtGui.QLabel(dial_groups)
        self.l_userGrpName.setMinimumSize(QtCore.QSize(92, 0))
        self.l_userGrpName.setMaximumSize(QtCore.QSize(92, 16777215))
        self.l_userGrpName.setObjectName(_fromUtf8("l_userGrpName"))
        self.hl_userGrpName.addWidget(self.l_userGrpName)
        self.le_userGrpName = QtGui.QLineEdit(dial_groups)
        self.le_userGrpName.setFrame(False)
        self.le_userGrpName.setObjectName(_fromUtf8("le_userGrpName"))
        self.hl_userGrpName.addWidget(self.le_userGrpName)
        self.gridLayout.addLayout(self.hl_userGrpName, 4, 0, 1, 1)
        self.hl_userGrpGrade = QtGui.QHBoxLayout()
        self.hl_userGrpGrade.setContentsMargins(-1, 0, -1, 0)
        self.hl_userGrpGrade.setObjectName(_fromUtf8("hl_userGrpGrade"))
        self.l_userGrpGrade = QtGui.QLabel(dial_groups)
        self.l_userGrpGrade.setMinimumSize(QtCore.QSize(92, 0))
        self.l_userGrpGrade.setMaximumSize(QtCore.QSize(92, 16777215))
        self.l_userGrpGrade.setObjectName(_fromUtf8("l_userGrpGrade"))
        self.hl_userGrpGrade.addWidget(self.l_userGrpGrade)
        self.cb_grade = QtGui.QComboBox(dial_groups)
        self.cb_grade.setObjectName(_fromUtf8("cb_grade"))
        self.hl_userGrpGrade.addWidget(self.cb_grade)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hl_userGrpGrade.addItem(spacerItem7)
        self.gridLayout.addLayout(self.hl_userGrpGrade, 5, 0, 1, 1)

        self.retranslateUi(dial_groups)
        QtCore.QMetaObject.connectSlotsByName(dial_groups)
        dial_groups.setTabOrder(self.le_userGrpCode, self.le_userGrpName)
        dial_groups.setTabOrder(self.le_userGrpName, self.cb_grade)
        dial_groups.setTabOrder(self.cb_grade, self.sb_styleR)
        dial_groups.setTabOrder(self.sb_styleR, self.sb_styleG)
        dial_groups.setTabOrder(self.sb_styleG, self.sb_styleB)
        dial_groups.setTabOrder(self.sb_styleB, self.pb_userGrpStyle)
        dial_groups.setTabOrder(self.pb_userGrpStyle, self.pb_save)
        dial_groups.setTabOrder(self.pb_save, self.pb_cancel)

    def retranslateUi(self, dial_groups):
        dial_groups.setWindowTitle(_translate("dial_groups", "UserGroups Dialog", None))
        self.pb_save.setText(_translate("dial_groups", "Save", None))
        self.pb_cancel.setText(_translate("dial_groups", "cancel", None))
        self.l_userGrpStyle.setText(_translate("dial_groups", "User Group Style: ", None))
        self.l_r.setText(_translate("dial_groups", "R:", None))
        self.l_g.setText(_translate("dial_groups", "G:", None))
        self.l_b.setText(_translate("dial_groups", "B:", None))
        self.l_message.setText(_translate("dial_groups", "Edit User Group", None))
        self.l_userGrpCode.setText(_translate("dial_groups", "User Group Code: ", None))
        self.l_userGrpName.setText(_translate("dial_groups", "User Group Name: ", None))
        self.l_userGrpGrade.setText(_translate("dial_groups", "User Group Grade:", None))

